# syntax=docker/dockerfile:1
FROM node:22-alpine

WORKDIR /app

# Copy dependencies
COPY package*.json ./
RUN npm install --omit=dev

# Copy backend code (including worker)
COPY . .

# Use a different entrypoint for the worker
CMD ["node", "worker/worker.js"]